/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: nitwit.friends (https://sketchfab.com/nitwit.friends)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hatch-t-rex-a0f64c308f6840ec9a38a83553caa667
Title: Hatch T-Rex
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei';


 function Dinozaur(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/hatch_t-rex.glb')
   const { actions } = useAnimations(animations, group);


  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="sketchfabtimeframe">
            <group name="Object_2" scale={0}>
              <group name="frame_3" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                <group name="RootNode">
                  <group name="Cube_6" position={[15, 110, 60]}>
                    <mesh
                      name="Cube_6_Mat2_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_6_Mat2_0.geometry}
                      material={materials['Mat.2']}
                    />
                  </group>
                  <group name="Cube_5" position={[-15, 110, 60]}>
                    <mesh
                      name="Cube_5_Mat2_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_5_Mat2_0.geometry}
                      material={materials['Mat.2']}
                    />
                  </group>
                  <group name="Cube" position={[-15, 90, 90.1]}>
                    <mesh
                      name="Cube_Mat2_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_Mat2_0.geometry}
                      material={materials['Mat.2']}
                    />
                  </group>
                  <group name="Cube_1" position={[15, 90, 90.1]}>
                    <mesh
                      name="Cube_1_Mat2_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_1_Mat2_0.geometry}
                      material={materials['Mat.2']}
                    />
                  </group>
                  <group name="Cube_7" position={[15, 120, 60]}>
                    <mesh
                      name="Cube_7_Mat3_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_7_Mat3_0.geometry}
                      material={materials['Mat.3']}
                    />
                  </group>
                  <group name="Cube_8" position={[-15, 120, 60]}>
                    <mesh
                      name="Cube_8_Mat3_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_8_Mat3_0.geometry}
                      material={materials['Mat.3']}
                    />
                  </group>
                  <group name="Cube_4" position={[25, 115, 60]}>
                    <mesh
                      name="Cube_4_Mat3_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_4_Mat3_0.geometry}
                      material={materials['Mat.3']}
                    />
                  </group>
                  <group name="Cube_3" position={[-25, 115, 60]}>
                    <mesh
                      name="Cube_3_Mat3_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_3_Mat3_0.geometry}
                      material={materials['Mat.3']}
                    />
                  </group>
                  <group name="Cube_2" position={[-35, -45, -45]}>
                    <mesh
                      name="Cube_2_Mat_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_2_Mat_0.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_16" position={[35, -45, -45]}>
                    <mesh
                      name="Cube_16_Mat_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_16_Mat_0.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_19" position={[0, 115, 60]}>
                    <mesh
                      name="Cube_19_Mat_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_19_Mat_0.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_18" position={[-25, 130, 60]}>
                    <mesh
                      name="Cube_18_Mat_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_18_Mat_0.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_2_2" position={[35, 115, 60]}>
                    <mesh
                      name="Cube_2_2_Mat_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_2_2_Mat_0.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_1_2" position={[-35, 115, 60]}>
                    <mesh
                      name="Cube_1_2_Mat_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_1_2_Mat_0.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_3_2" position={[25, 130, 60]}>
                    <mesh
                      name="Cube_3_2_Mat_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_3_2_Mat_0.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_17" position={[10.666, 65, -100]}>
                    <mesh
                      name="Cube_17_Mat_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_17_Mat_0.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_10" position={[0, 65, -110]}>
                    <mesh
                      name="Cube_10_Mat_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_10_Mat_0.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_15" position={[-35, 80, 80]}>
                    <mesh
                      name="Cube_15_Mat_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_15_Mat_0.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_4_2">
                    <mesh
                      name="Cube_4_2_Mat_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_4_2_Mat_0.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_1_3" position={[0, 50, 20]}>
                    <mesh
                      name="Cube_1_3_Mat_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_1_3_Mat_0.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_2_3" position={[0, 80, 50]}>
                    <mesh
                      name="Cube_2_3_Mat_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_2_3_Mat_0.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_3_3" position={[0, 115, 45]}>
                    <mesh
                      name="Cube_3_3_Mat_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_3_3_Mat_0.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_5_2" position={[0, 95, 85]}>
                    <mesh
                      name="Cube_5_2_Mat_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_5_2_Mat_0.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_6_2" position={[0, -15, -85]}>
                    <mesh
                      name="Cube_6_2_Mat_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_6_2_Mat_0.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_7_2" position={[0, -5, -105]}>
                    <mesh
                      name="Cube_7_2_Mat_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_7_2_Mat_0.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_8_2" position={[0, 10, -110]}>
                    <mesh
                      name="Cube_8_2_Mat_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_8_2_Mat_0.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_9" position={[0, 40, -120]}>
                    <mesh
                      name="Cube_9_Mat_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_9_Mat_0.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_11" position={[30, 20, 85]}>
                    <mesh
                      name="Cube_11_Mat_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_11_Mat_0.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_12" position={[-30, 30, 85]}>
                    <mesh
                      name="Cube_12_Mat_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_12_Mat_0.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_13" position={[30, 10, 100]}>
                    <mesh
                      name="Cube_13_Mat_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_13_Mat_0.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_14" position={[-30, 20, 100]}>
                    <mesh
                      name="Cube_14_Mat_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_14_Mat_0.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_4_3" position={[35, 80, 80]}>
                    <mesh
                      name="Cube_4_3_Mat_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_4_3_Mat_0.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_5_3" position={[45, -25, 0]}>
                    <mesh
                      name="Cube_5_3_Mat_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_5_3_Mat_0.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_1_4" position={[45, -60, -10]}>
                    <mesh
                      name="Cube_1_4_Mat_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_1_4_Mat_0.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_2_4" position={[45, -75, -5]}>
                    <mesh
                      name="Cube_2_4_Mat_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_2_4_Mat_0.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_3_4" position={[45, -85, -5]}>
                    <mesh
                      name="Cube_3_4_Mat_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_3_4_Mat_0.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_4_4" position={[45, -95, -15]}>
                    <mesh
                      name="Cube_4_4_Mat_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_4_4_Mat_0.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_5_4" position={[45, -105, -15]}>
                    <mesh
                      name="Cube_5_4_Mat_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_5_4_Mat_0.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_12_2" position={[40, -24, 25]}>
                    <mesh
                      name="Cube_12_2_Mat1_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_12_2_Mat1_0.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_14_2" position={[40, -24, -1]}>
                    <mesh
                      name="Cube_14_2_Mat1_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_14_2_Mat1_0.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_11_2" position={[-40, -24, 25]}>
                    <mesh
                      name="Cube_11_2_Mat1_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_11_2_Mat1_0.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_6_3" position={[-40, -24, -1]}>
                    <mesh
                      name="Cube_6_3_Mat1_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_6_3_Mat1_0.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_2_5" position={[0, -20, -100]}>
                    <mesh
                      name="Cube_2_5_Mat1_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_2_5_Mat1_0.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_7_3" position={[0, -35, -85]}>
                    <mesh
                      name="Cube_7_3_Mat1_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_7_3_Mat1_0.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_4_5" position={[0, 80, 80]}>
                    <mesh
                      name="Cube_4_5_Mat1_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_4_5_Mat1_0.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_6_4" position={[0, 20, 80]}>
                    <mesh
                      name="Cube_6_4_Mat1_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_6_4_Mat1_0.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_1_5" position={[0, 80, 90]}>
                    <mesh
                      name="Cube_1_5_Mat1_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_1_5_Mat1_0.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_13_2" position={[30, -5, 100]}>
                    <mesh
                      name="Cube_13_2_Mat1_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_13_2_Mat1_0.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_7_4" position={[-30, 5, 100]}>
                    <mesh
                      name="Cube_7_4_Mat1_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_7_4_Mat1_0.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_6_5" position={[-35, -85, 40]}>
                    <mesh
                      name="Cube_6_5_Mat1_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_6_5_Mat1_0.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_7_5" position={[-55, -85, 40]}>
                    <mesh
                      name="Cube_7_5_Mat1_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_7_5_Mat1_0.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_6_6" position={[55, -105, 10]}>
                    <mesh
                      name="Cube_6_6_Mat1_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_6_6_Mat1_0.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_7_6" position={[35, -105, 10]}>
                    <mesh
                      name="Cube_7_6_Mat1_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_7_6_Mat1_0.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_3_5" position={[0, 30, -130]}>
                    <mesh
                      name="Cube_3_5_Mat1_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_3_5_Mat1_0.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_5_5" position={[10, 75, -110]}>
                    <mesh
                      name="Cube_5_5_Mat1_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_5_5_Mat1_0.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_5_6" position={[0, 40, -5]}>
                    <mesh
                      name="Cube_5_6_Mat1_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_5_6_Mat1_0.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_9_2" position={[0, 80, 44]}>
                    <mesh
                      name="Cube_9_2_Mat1_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_9_2_Mat1_0.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_8_3" position={[0, 20, -55]}>
                    <mesh
                      name="Cube_8_3_Mat1_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_8_3_Mat1_0.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_10_2" position={[0, -5, -90]}>
                    <mesh
                      name="Cube_10_2_Mat1_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_10_2_Mat1_0.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_8_4" position={[-45, -25, 0]}>
                    <mesh
                      name="Cube_8_4_Mat_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_8_4_Mat_0.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_1_6" position={[-45, -60, -10]}>
                    <mesh
                      name="Cube_1_6_Mat_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_1_6_Mat_0.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_2_6" position={[-45, -65, 5]}>
                    <mesh
                      name="Cube_2_6_Mat_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_2_6_Mat_0.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_3_6" position={[-45, -75, 5]}>
                    <mesh
                      name="Cube_3_6_Mat_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_3_6_Mat_0.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_4_6" position={[-45, -75, 15]}>
                    <mesh
                      name="Cube_4_6_Mat_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_4_6_Mat_0.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_5_7" position={[-45, -85, 15]}>
                    <mesh
                      name="Cube_5_7_Mat_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_5_7_Mat_0.geometry}
                      material={materials.material}
                    />
                  </group>
                </group>
              </group>
            </group>
            <group name="Object_135" scale={0}>
              <group name="frame_2" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                <group name="RootNode_1">
                  <group name="Cube_6_1" position={[15, 115, 60]}>
                    <mesh
                      name="Cube_6_Mat2_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_6_Mat2_0_1.geometry}
                      material={materials['Mat.2']}
                    />
                  </group>
                  <group name="Cube_5_1" position={[-15, 115, 60]}>
                    <mesh
                      name="Cube_5_Mat2_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_5_Mat2_0_1.geometry}
                      material={materials['Mat.2']}
                    />
                  </group>
                  <group name="Cube_1" position={[-15, 95, 90.1]}>
                    <mesh
                      name="Cube_Mat2_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_Mat2_0_1.geometry}
                      material={materials['Mat.2']}
                    />
                  </group>
                  <group name="Cube_1_1" position={[15, 95, 90.1]}>
                    <mesh
                      name="Cube_1_Mat2_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_1_Mat2_0_1.geometry}
                      material={materials['Mat.2']}
                    />
                  </group>
                  <group name="Cube_7_1" position={[15, 125, 60]}>
                    <mesh
                      name="Cube_7_Mat3_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_7_Mat3_0_1.geometry}
                      material={materials['Mat.3']}
                    />
                  </group>
                  <group name="Cube_8_1" position={[-15, 125, 60]}>
                    <mesh
                      name="Cube_8_Mat3_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_8_Mat3_0_1.geometry}
                      material={materials['Mat.3']}
                    />
                  </group>
                  <group name="Cube_4_1" position={[25, 120, 60]}>
                    <mesh
                      name="Cube_4_Mat3_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_4_Mat3_0_1.geometry}
                      material={materials['Mat.3']}
                    />
                  </group>
                  <group name="Cube_3_1" position={[-25, 120, 60]}>
                    <mesh
                      name="Cube_3_Mat3_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_3_Mat3_0_1.geometry}
                      material={materials['Mat.3']}
                    />
                  </group>
                  <group name="Cube_2_1" position={[-35, -45, -45]}>
                    <mesh
                      name="Cube_2_Mat_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_2_Mat_0_1.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_16_1" position={[35, -45, -45]}>
                    <mesh
                      name="Cube_16_Mat_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_16_Mat_0_1.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_19_1" position={[0, 120, 60]}>
                    <mesh
                      name="Cube_19_Mat_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_19_Mat_0_1.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_18_1" position={[-25, 135, 60]}>
                    <mesh
                      name="Cube_18_Mat_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_18_Mat_0_1.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_2_2_1" position={[35, 120, 60]}>
                    <mesh
                      name="Cube_2_2_Mat_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_2_2_Mat_0_1.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_1_2_1" position={[-35, 120, 60]}>
                    <mesh
                      name="Cube_1_2_Mat_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_1_2_Mat_0_1.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_3_2_1" position={[25, 135, 60]}>
                    <mesh
                      name="Cube_3_2_Mat_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_3_2_Mat_0_1.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_17_1" position={[0, 65, -100]}>
                    <mesh
                      name="Cube_17_Mat_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_17_Mat_0_1.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_10_1" position={[0, 65, -110]}>
                    <mesh
                      name="Cube_10_Mat_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_10_Mat_0_1.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_15_1" position={[-35, 85, 80]}>
                    <mesh
                      name="Cube_15_Mat_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_15_Mat_0_1.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_4_2_1">
                    <mesh
                      name="Cube_4_2_Mat_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_4_2_Mat_0_1.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_1_3_1" position={[0, 50, 20]}>
                    <mesh
                      name="Cube_1_3_Mat_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_1_3_Mat_0_1.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_2_3_1" position={[0, 85, 50]}>
                    <mesh
                      name="Cube_2_3_Mat_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_2_3_Mat_0_1.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_3_3_1" position={[0, 120, 45]}>
                    <mesh
                      name="Cube_3_3_Mat_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_3_3_Mat_0_1.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_5_2_1" position={[0, 100, 85]}>
                    <mesh
                      name="Cube_5_2_Mat_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_5_2_Mat_0_1.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_6_2_1" position={[0, -15, -85]}>
                    <mesh
                      name="Cube_6_2_Mat_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_6_2_Mat_0_1.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_7_2_1" position={[0, -5, -105]}>
                    <mesh
                      name="Cube_7_2_Mat_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_7_2_Mat_0_1.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_8_2_1" position={[0, 10, -110]}>
                    <mesh
                      name="Cube_8_2_Mat_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_8_2_Mat_0_1.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_9_1" position={[0, 40, -120]}>
                    <mesh
                      name="Cube_9_Mat_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_9_Mat_0_1.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_11_1" position={[30, 30, 85]}>
                    <mesh
                      name="Cube_11_Mat_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_11_Mat_0_1.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_12_1" position={[-30, 30, 85]}>
                    <mesh
                      name="Cube_12_Mat_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_12_Mat_0_1.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_13_1" position={[30, 20, 100]}>
                    <mesh
                      name="Cube_13_Mat_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_13_Mat_0_1.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_14_1" position={[-30, 20, 100]}>
                    <mesh
                      name="Cube_14_Mat_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_14_Mat_0_1.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_4_3_1" position={[35, 85, 80]}>
                    <mesh
                      name="Cube_4_3_Mat_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_4_3_Mat_0_1.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_5_3_1" position={[45, -25, 0]}>
                    <mesh
                      name="Cube_5_3_Mat_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_5_3_Mat_0_1.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_1_4_1" position={[45, -60, -10]}>
                    <mesh
                      name="Cube_1_4_Mat_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_1_4_Mat_0_1.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_2_4_1" position={[45, -75, -5]}>
                    <mesh
                      name="Cube_2_4_Mat_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_2_4_Mat_0_1.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_3_4_1" position={[45, -85, -5]}>
                    <mesh
                      name="Cube_3_4_Mat_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_3_4_Mat_0_1.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_4_4_1" position={[45, -95, -5]}>
                    <mesh
                      name="Cube_4_4_Mat_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_4_4_Mat_0_1.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_5_4_1" position={[45, -105, -5]}>
                    <mesh
                      name="Cube_5_4_Mat_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_5_4_Mat_0_1.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_12_2_1" position={[40, -24, 25]}>
                    <mesh
                      name="Cube_12_2_Mat1_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_12_2_Mat1_0_1.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_14_2_1" position={[40, -24, -1]}>
                    <mesh
                      name="Cube_14_2_Mat1_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_14_2_Mat1_0_1.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_11_2_1" position={[-40, -24, 25]}>
                    <mesh
                      name="Cube_11_2_Mat1_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_11_2_Mat1_0_1.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_6_3_1" position={[-40, -24, -1]}>
                    <mesh
                      name="Cube_6_3_Mat1_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_6_3_Mat1_0_1.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_2_5_1" position={[0, -20, -100]}>
                    <mesh
                      name="Cube_2_5_Mat1_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_2_5_Mat1_0_1.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_7_3_1" position={[0, -35, -85]}>
                    <mesh
                      name="Cube_7_3_Mat1_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_7_3_Mat1_0_1.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_4_5_1" position={[0, 85, 80]}>
                    <mesh
                      name="Cube_4_5_Mat1_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_4_5_Mat1_0_1.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_6_4_1" position={[0, 20, 80]}>
                    <mesh
                      name="Cube_6_4_Mat1_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_6_4_Mat1_0_1.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_1_5_1" position={[0, 85, 90]}>
                    <mesh
                      name="Cube_1_5_Mat1_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_1_5_Mat1_0_1.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_13_2_1" position={[30, 5, 100]}>
                    <mesh
                      name="Cube_13_2_Mat1_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_13_2_Mat1_0_1.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_7_4_1" position={[-30, 5, 100]}>
                    <mesh
                      name="Cube_7_4_Mat1_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_7_4_Mat1_0_1.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_6_5_1" position={[-35, -105, 20]}>
                    <mesh
                      name="Cube_6_5_Mat1_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_6_5_Mat1_0_1.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_7_5_1" position={[-55, -105, 20]}>
                    <mesh
                      name="Cube_7_5_Mat1_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_7_5_Mat1_0_1.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_6_6_1" position={[55, -105, 20]}>
                    <mesh
                      name="Cube_6_6_Mat1_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_6_6_Mat1_0_1.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_7_6_1" position={[35, -105, 20]}>
                    <mesh
                      name="Cube_7_6_Mat1_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_7_6_Mat1_0_1.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_3_5_1" position={[0, 30, -130]}>
                    <mesh
                      name="Cube_3_5_Mat1_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_3_5_Mat1_0_1.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_5_5_1" position={[0, 75, -110]}>
                    <mesh
                      name="Cube_5_5_Mat1_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_5_5_Mat1_0_1.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_5_6_1" position={[0, 40, -5]}>
                    <mesh
                      name="Cube_5_6_Mat1_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_5_6_Mat1_0_1.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_9_2_1" position={[0, 85, 44]}>
                    <mesh
                      name="Cube_9_2_Mat1_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_9_2_Mat1_0_1.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_8_3_1" position={[0, 20, -55]}>
                    <mesh
                      name="Cube_8_3_Mat1_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_8_3_Mat1_0_1.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_10_2_1" position={[0, -5, -90]}>
                    <mesh
                      name="Cube_10_2_Mat1_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_10_2_Mat1_0_1.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_8_4_1" position={[-45, -25, 0]}>
                    <mesh
                      name="Cube_8_4_Mat_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_8_4_Mat_0_1.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_1_6_1" position={[-45, -60, -10]}>
                    <mesh
                      name="Cube_1_6_Mat_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_1_6_Mat_0_1.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_2_6_1" position={[-45, -75, -5]}>
                    <mesh
                      name="Cube_2_6_Mat_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_2_6_Mat_0_1.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_3_6_1" position={[-45, -85, -5]}>
                    <mesh
                      name="Cube_3_6_Mat_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_3_6_Mat_0_1.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_4_6_1" position={[-45, -95, -5]}>
                    <mesh
                      name="Cube_4_6_Mat_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_4_6_Mat_0_1.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_5_7_1" position={[-45, -105, -5]}>
                    <mesh
                      name="Cube_5_7_Mat_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_5_7_Mat_0_1.geometry}
                      material={materials.material}
                    />
                  </group>
                </group>
              </group>
            </group>
            <group name="Object_268" scale={0}>
              <group name="frame_1" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                <group name="RootNode_2">
                  <group name="Cube_6_2" position={[15, 110, 60]}>
                    <mesh
                      name="Cube_6_Mat2_0_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_6_Mat2_0_2.geometry}
                      material={materials['Mat.2']}
                    />
                  </group>
                  <group name="Cube_5_2" position={[-15, 110, 60]}>
                    <mesh
                      name="Cube_5_Mat2_0_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_5_Mat2_0_2.geometry}
                      material={materials['Mat.2']}
                    />
                  </group>
                  <group name="Cube_2" position={[-15, 90, 90.1]}>
                    <mesh
                      name="Cube_Mat2_0_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_Mat2_0_2.geometry}
                      material={materials['Mat.2']}
                    />
                  </group>
                  <group name="Cube_1_2" position={[15, 90, 90.1]}>
                    <mesh
                      name="Cube_1_Mat2_0_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_1_Mat2_0_2.geometry}
                      material={materials['Mat.2']}
                    />
                  </group>
                  <group name="Cube_7_2" position={[15, 120, 60]}>
                    <mesh
                      name="Cube_7_Mat3_0_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_7_Mat3_0_2.geometry}
                      material={materials['Mat.3']}
                    />
                  </group>
                  <group name="Cube_8_2" position={[-15, 120, 60]}>
                    <mesh
                      name="Cube_8_Mat3_0_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_8_Mat3_0_2.geometry}
                      material={materials['Mat.3']}
                    />
                  </group>
                  <group name="Cube_4_2" position={[25, 115, 60]}>
                    <mesh
                      name="Cube_4_Mat3_0_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_4_Mat3_0_2.geometry}
                      material={materials['Mat.3']}
                    />
                  </group>
                  <group name="Cube_3_2" position={[-25, 115, 60]}>
                    <mesh
                      name="Cube_3_Mat3_0_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_3_Mat3_0_2.geometry}
                      material={materials['Mat.3']}
                    />
                  </group>
                  <group name="Cube_2_2" position={[-35, -45, -45]}>
                    <mesh
                      name="Cube_2_Mat_0_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_2_Mat_0_2.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_16_2" position={[35, -45, -45]}>
                    <mesh
                      name="Cube_16_Mat_0_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_16_Mat_0_2.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_19_2" position={[0, 115, 60]}>
                    <mesh
                      name="Cube_19_Mat_0_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_19_Mat_0_2.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_18_2" position={[-25, 130, 60]}>
                    <mesh
                      name="Cube_18_Mat_0_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_18_Mat_0_2.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_2_2_2" position={[35, 115, 60]}>
                    <mesh
                      name="Cube_2_2_Mat_0_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_2_2_Mat_0_2.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_1_2_2" position={[-35, 115, 60]}>
                    <mesh
                      name="Cube_1_2_Mat_0_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_1_2_Mat_0_2.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_3_2_2" position={[25, 130, 60]}>
                    <mesh
                      name="Cube_3_2_Mat_0_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_3_2_Mat_0_2.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_17_2" position={[-10, 65, -100]}>
                    <mesh
                      name="Cube_17_Mat_0_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_17_Mat_0_2.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_10_2" position={[0, 65, -110]}>
                    <mesh
                      name="Cube_10_Mat_0_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_10_Mat_0_2.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_15_2" position={[-35, 80, 80]}>
                    <mesh
                      name="Cube_15_Mat_0_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_15_Mat_0_2.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_4_2_2">
                    <mesh
                      name="Cube_4_2_Mat_0_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_4_2_Mat_0_2.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_1_3_2" position={[0, 50, 20]}>
                    <mesh
                      name="Cube_1_3_Mat_0_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_1_3_Mat_0_2.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_2_3_2" position={[0, 80, 50]}>
                    <mesh
                      name="Cube_2_3_Mat_0_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_2_3_Mat_0_2.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_3_3_2" position={[0, 115, 45]}>
                    <mesh
                      name="Cube_3_3_Mat_0_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_3_3_Mat_0_2.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_5_2_2" position={[0, 95, 85]}>
                    <mesh
                      name="Cube_5_2_Mat_0_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_5_2_Mat_0_2.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_6_2_2" position={[0, -15, -85]}>
                    <mesh
                      name="Cube_6_2_Mat_0_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_6_2_Mat_0_2.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_7_2_2" position={[0, -5, -105]}>
                    <mesh
                      name="Cube_7_2_Mat_0_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_7_2_Mat_0_2.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_8_2_2" position={[0, 10, -110]}>
                    <mesh
                      name="Cube_8_2_Mat_0_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_8_2_Mat_0_2.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_9_2" position={[0, 40, -120]}>
                    <mesh
                      name="Cube_9_Mat_0_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_9_Mat_0_2.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_11_2" position={[30, 30, 85]}>
                    <mesh
                      name="Cube_11_Mat_0_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_11_Mat_0_2.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_12_2" position={[-30, 20, 85]}>
                    <mesh
                      name="Cube_12_Mat_0_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_12_Mat_0_2.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_13_2" position={[30, 20, 100]}>
                    <mesh
                      name="Cube_13_Mat_0_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_13_Mat_0_2.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_14_2" position={[-30, 10, 100]}>
                    <mesh
                      name="Cube_14_Mat_0_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_14_Mat_0_2.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_4_3_2" position={[35, 80, 80]}>
                    <mesh
                      name="Cube_4_3_Mat_0_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_4_3_Mat_0_2.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_5_3_2" position={[45, -25, 0]}>
                    <mesh
                      name="Cube_5_3_Mat_0_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_5_3_Mat_0_2.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_1_4_2" position={[45, -60, -10]}>
                    <mesh
                      name="Cube_1_4_Mat_0_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_1_4_Mat_0_2.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_2_4_2" position={[45, -65, 5]}>
                    <mesh
                      name="Cube_2_4_Mat_0_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_2_4_Mat_0_2.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_3_4_2" position={[45, -75, 5]}>
                    <mesh
                      name="Cube_3_4_Mat_0_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_3_4_Mat_0_2.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_4_4_2" position={[45, -75, 15]}>
                    <mesh
                      name="Cube_4_4_Mat_0_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_4_4_Mat_0_2.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_5_4_2" position={[45, -85, 15]}>
                    <mesh
                      name="Cube_5_4_Mat_0_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_5_4_Mat_0_2.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_12_2_2" position={[40, -24, 25]}>
                    <mesh
                      name="Cube_12_2_Mat1_0_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_12_2_Mat1_0_2.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_14_2_2" position={[40, -24, -1]}>
                    <mesh
                      name="Cube_14_2_Mat1_0_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_14_2_Mat1_0_2.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_11_2_2" position={[-40, -24, 25]}>
                    <mesh
                      name="Cube_11_2_Mat1_0_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_11_2_Mat1_0_2.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_6_3_2" position={[-40, -24, -1]}>
                    <mesh
                      name="Cube_6_3_Mat1_0_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_6_3_Mat1_0_2.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_2_5_2" position={[0, -20, -100]}>
                    <mesh
                      name="Cube_2_5_Mat1_0_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_2_5_Mat1_0_2.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_7_3_2" position={[0, -35, -85]}>
                    <mesh
                      name="Cube_7_3_Mat1_0_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_7_3_Mat1_0_2.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_4_5_2" position={[0, 80, 80]}>
                    <mesh
                      name="Cube_4_5_Mat1_0_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_4_5_Mat1_0_2.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_6_4_2" position={[0, 20, 80]}>
                    <mesh
                      name="Cube_6_4_Mat1_0_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_6_4_Mat1_0_2.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_1_5_2" position={[0, 80, 90]}>
                    <mesh
                      name="Cube_1_5_Mat1_0_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_1_5_Mat1_0_2.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_13_2_2" position={[30, 5, 100]}>
                    <mesh
                      name="Cube_13_2_Mat1_0_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_13_2_Mat1_0_2.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_7_4_2" position={[-30, -5, 100]}>
                    <mesh
                      name="Cube_7_4_Mat1_0_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_7_4_Mat1_0_2.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_6_5_2" position={[-35, -105, 10]}>
                    <mesh
                      name="Cube_6_5_Mat1_0_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_6_5_Mat1_0_2.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_7_5_2" position={[-55, -105, 10]}>
                    <mesh
                      name="Cube_7_5_Mat1_0_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_7_5_Mat1_0_2.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_6_6_2" position={[55, -85, 40]}>
                    <mesh
                      name="Cube_6_6_Mat1_0_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_6_6_Mat1_0_2.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_7_6_2" position={[35, -85, 40]}>
                    <mesh
                      name="Cube_7_6_Mat1_0_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_7_6_Mat1_0_2.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_3_5_2" position={[0, 30, -130]}>
                    <mesh
                      name="Cube_3_5_Mat1_0_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_3_5_Mat1_0_2.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_5_5_2" position={[-10, 75, -110]}>
                    <mesh
                      name="Cube_5_5_Mat1_0_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_5_5_Mat1_0_2.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_5_6_2" position={[0, 40, -5]}>
                    <mesh
                      name="Cube_5_6_Mat1_0_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_5_6_Mat1_0_2.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_9_2_2" position={[0, 80, 44]}>
                    <mesh
                      name="Cube_9_2_Mat1_0_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_9_2_Mat1_0_2.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_8_3_2" position={[0, 20, -55]}>
                    <mesh
                      name="Cube_8_3_Mat1_0_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_8_3_Mat1_0_2.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_10_2_2" position={[0, -5, -90]}>
                    <mesh
                      name="Cube_10_2_Mat1_0_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_10_2_Mat1_0_2.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_8_4_2" position={[-45, -25, 0]}>
                    <mesh
                      name="Cube_8_4_Mat_0_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_8_4_Mat_0_2.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_1_6_2" position={[-45, -60, -10]}>
                    <mesh
                      name="Cube_1_6_Mat_0_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_1_6_Mat_0_2.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_2_6_2" position={[-45, -75, -5]}>
                    <mesh
                      name="Cube_2_6_Mat_0_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_2_6_Mat_0_2.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_3_6_2" position={[-45, -85, -5]}>
                    <mesh
                      name="Cube_3_6_Mat_0_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_3_6_Mat_0_2.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_4_6_2" position={[-45, -95, -15]}>
                    <mesh
                      name="Cube_4_6_Mat_0_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_4_6_Mat_0_2.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_5_7_2" position={[-45, -105, -15]}>
                    <mesh
                      name="Cube_5_7_Mat_0_2"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_5_7_Mat_0_2.geometry}
                      material={materials.material}
                    />
                  </group>
                </group>
              </group>
            </group>
            <group name="Object_401">
              <group name="frame_2_1" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                <group name="RootNode_3">
                  <group name="Cube_6_3" position={[15, 115, 60]}>
                    <mesh
                      name="Cube_6_Mat2_0_3"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_6_Mat2_0_3.geometry}
                      material={materials['Mat.2']}
                    />
                  </group>
                  <group name="Cube_5_3" position={[-15, 115, 60]}>
                    <mesh
                      name="Cube_5_Mat2_0_3"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_5_Mat2_0_3.geometry}
                      material={materials['Mat.2']}
                    />
                  </group>
                  <group name="Cube_3" position={[-15, 95, 90.1]}>
                    <mesh
                      name="Cube_Mat2_0_3"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_Mat2_0_3.geometry}
                      material={materials['Mat.2']}
                    />
                  </group>
                  <group name="Cube_1_3" position={[15, 95, 90.1]}>
                    <mesh
                      name="Cube_1_Mat2_0_3"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_1_Mat2_0_3.geometry}
                      material={materials['Mat.2']}
                    />
                  </group>
                  <group name="Cube_7_3" position={[15, 125, 60]}>
                    <mesh
                      name="Cube_7_Mat3_0_3"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_7_Mat3_0_3.geometry}
                      material={materials['Mat.3']}
                    />
                  </group>
                  <group name="Cube_8_3" position={[-15, 125, 60]}>
                    <mesh
                      name="Cube_8_Mat3_0_3"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_8_Mat3_0_3.geometry}
                      material={materials['Mat.3']}
                    />
                  </group>
                  <group name="Cube_4_3" position={[25, 120, 60]}>
                    <mesh
                      name="Cube_4_Mat3_0_3"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_4_Mat3_0_3.geometry}
                      material={materials['Mat.3']}
                    />
                  </group>
                  <group name="Cube_3_3" position={[-25, 120, 60]}>
                    <mesh
                      name="Cube_3_Mat3_0_3"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_3_Mat3_0_3.geometry}
                      material={materials['Mat.3']}
                    />
                  </group>
                  <group name="Cube_2_3" position={[-35, -45, -45]}>
                    <mesh
                      name="Cube_2_Mat_0_3"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_2_Mat_0_3.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_16_3" position={[35, -45, -45]}>
                    <mesh
                      name="Cube_16_Mat_0_3"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_16_Mat_0_3.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_19_3" position={[0, 120, 60]}>
                    <mesh
                      name="Cube_19_Mat_0_3"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_19_Mat_0_3.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_18_3" position={[-25, 135, 60]}>
                    <mesh
                      name="Cube_18_Mat_0_3"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_18_Mat_0_3.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_2_2_3" position={[35, 120, 60]}>
                    <mesh
                      name="Cube_2_2_Mat_0_3"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_2_2_Mat_0_3.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_1_2_3" position={[-35, 120, 60]}>
                    <mesh
                      name="Cube_1_2_Mat_0_3"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_1_2_Mat_0_3.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_3_2_3" position={[25, 135, 60]}>
                    <mesh
                      name="Cube_3_2_Mat_0_3"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_3_2_Mat_0_3.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_17_3" position={[0, 65, -100]}>
                    <mesh
                      name="Cube_17_Mat_0_3"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_17_Mat_0_3.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_10_3" position={[0, 65, -110]}>
                    <mesh
                      name="Cube_10_Mat_0_3"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_10_Mat_0_3.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_15_3" position={[-35, 85, 80]}>
                    <mesh
                      name="Cube_15_Mat_0_3"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_15_Mat_0_3.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_4_2_3">
                    <mesh
                      name="Cube_4_2_Mat_0_3"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_4_2_Mat_0_3.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_1_3_3" position={[0, 50, 20]}>
                    <mesh
                      name="Cube_1_3_Mat_0_3"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_1_3_Mat_0_3.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_2_3_3" position={[0, 85, 50]}>
                    <mesh
                      name="Cube_2_3_Mat_0_3"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_2_3_Mat_0_3.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_3_3_3" position={[0, 120, 45]}>
                    <mesh
                      name="Cube_3_3_Mat_0_3"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_3_3_Mat_0_3.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_5_2_3" position={[0, 100, 85]}>
                    <mesh
                      name="Cube_5_2_Mat_0_3"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_5_2_Mat_0_3.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_6_2_3" position={[0, -15, -85]}>
                    <mesh
                      name="Cube_6_2_Mat_0_3"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_6_2_Mat_0_3.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_7_2_3" position={[0, -5, -105]}>
                    <mesh
                      name="Cube_7_2_Mat_0_3"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_7_2_Mat_0_3.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_8_2_3" position={[0, 10, -110]}>
                    <mesh
                      name="Cube_8_2_Mat_0_3"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_8_2_Mat_0_3.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_9_3" position={[0, 40, -120]}>
                    <mesh
                      name="Cube_9_Mat_0_3"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_9_Mat_0_3.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_11_3" position={[30, 30, 85]}>
                    <mesh
                      name="Cube_11_Mat_0_3"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_11_Mat_0_3.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_12_3" position={[-30, 30, 85]}>
                    <mesh
                      name="Cube_12_Mat_0_3"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_12_Mat_0_3.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_13_3" position={[30, 20, 100]}>
                    <mesh
                      name="Cube_13_Mat_0_3"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_13_Mat_0_3.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_14_3" position={[-30, 20, 100]}>
                    <mesh
                      name="Cube_14_Mat_0_3"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_14_Mat_0_3.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_4_3_3" position={[35, 85, 80]}>
                    <mesh
                      name="Cube_4_3_Mat_0_3"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_4_3_Mat_0_3.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_5_3_3" position={[45, -25, 0]}>
                    <mesh
                      name="Cube_5_3_Mat_0_3"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_5_3_Mat_0_3.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_1_4_3" position={[45, -60, -10]}>
                    <mesh
                      name="Cube_1_4_Mat_0_3"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_1_4_Mat_0_3.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_2_4_3" position={[45, -75, -5]}>
                    <mesh
                      name="Cube_2_4_Mat_0_3"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_2_4_Mat_0_3.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_3_4_3" position={[45, -85, -5]}>
                    <mesh
                      name="Cube_3_4_Mat_0_3"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_3_4_Mat_0_3.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_4_4_3" position={[45, -95, -5]}>
                    <mesh
                      name="Cube_4_4_Mat_0_3"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_4_4_Mat_0_3.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_5_4_3" position={[45, -105, -5]}>
                    <mesh
                      name="Cube_5_4_Mat_0_3"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_5_4_Mat_0_3.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_12_2_3" position={[40, -24, 25]}>
                    <mesh
                      name="Cube_12_2_Mat1_0_3"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_12_2_Mat1_0_3.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_14_2_3" position={[40, -24, -1]}>
                    <mesh
                      name="Cube_14_2_Mat1_0_3"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_14_2_Mat1_0_3.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_11_2_3" position={[-40, -24, 25]}>
                    <mesh
                      name="Cube_11_2_Mat1_0_3"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_11_2_Mat1_0_3.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_6_3_3" position={[-40, -24, -1]}>
                    <mesh
                      name="Cube_6_3_Mat1_0_3"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_6_3_Mat1_0_3.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_2_5_3" position={[0, -20, -100]}>
                    <mesh
                      name="Cube_2_5_Mat1_0_3"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_2_5_Mat1_0_3.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_7_3_3" position={[0, -35, -85]}>
                    <mesh
                      name="Cube_7_3_Mat1_0_3"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_7_3_Mat1_0_3.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_4_5_3" position={[0, 85, 80]}>
                    <mesh
                      name="Cube_4_5_Mat1_0_3"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_4_5_Mat1_0_3.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_6_4_3" position={[0, 20, 80]}>
                    <mesh
                      name="Cube_6_4_Mat1_0_3"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_6_4_Mat1_0_3.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_1_5_3" position={[0, 85, 90]}>
                    <mesh
                      name="Cube_1_5_Mat1_0_3"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_1_5_Mat1_0_3.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_13_2_3" position={[30, 5, 100]}>
                    <mesh
                      name="Cube_13_2_Mat1_0_3"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_13_2_Mat1_0_3.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_7_4_3" position={[-30, 5, 100]}>
                    <mesh
                      name="Cube_7_4_Mat1_0_3"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_7_4_Mat1_0_3.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_6_5_3" position={[-35, -105, 20]}>
                    <mesh
                      name="Cube_6_5_Mat1_0_3"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_6_5_Mat1_0_3.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_7_5_3" position={[-55, -105, 20]}>
                    <mesh
                      name="Cube_7_5_Mat1_0_3"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_7_5_Mat1_0_3.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_6_6_3" position={[55, -105, 20]}>
                    <mesh
                      name="Cube_6_6_Mat1_0_3"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_6_6_Mat1_0_3.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_7_6_3" position={[35, -105, 20]}>
                    <mesh
                      name="Cube_7_6_Mat1_0_3"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_7_6_Mat1_0_3.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_3_5_3" position={[0, 30, -130]}>
                    <mesh
                      name="Cube_3_5_Mat1_0_3"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_3_5_Mat1_0_3.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_5_5_3" position={[0, 75, -110]}>
                    <mesh
                      name="Cube_5_5_Mat1_0_3"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_5_5_Mat1_0_3.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_5_6_3" position={[0, 40, -5]}>
                    <mesh
                      name="Cube_5_6_Mat1_0_3"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_5_6_Mat1_0_3.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_9_2_3" position={[0, 85, 44]}>
                    <mesh
                      name="Cube_9_2_Mat1_0_3"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_9_2_Mat1_0_3.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_8_3_3" position={[0, 20, -55]}>
                    <mesh
                      name="Cube_8_3_Mat1_0_3"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_8_3_Mat1_0_3.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_10_2_3" position={[0, -5, -90]}>
                    <mesh
                      name="Cube_10_2_Mat1_0_3"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_10_2_Mat1_0_3.geometry}
                      material={materials['Mat.1']}
                    />
                  </group>
                  <group name="Cube_8_4_3" position={[-45, -25, 0]}>
                    <mesh
                      name="Cube_8_4_Mat_0_3"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_8_4_Mat_0_3.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_1_6_3" position={[-45, -60, -10]}>
                    <mesh
                      name="Cube_1_6_Mat_0_3"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_1_6_Mat_0_3.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_2_6_3" position={[-45, -75, -5]}>
                    <mesh
                      name="Cube_2_6_Mat_0_3"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_2_6_Mat_0_3.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_3_6_3" position={[-45, -85, -5]}>
                    <mesh
                      name="Cube_3_6_Mat_0_3"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_3_6_Mat_0_3.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_4_6_3" position={[-45, -95, -5]}>
                    <mesh
                      name="Cube_4_6_Mat_0_3"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_4_6_Mat_0_3.geometry}
                      material={materials.material}
                    />
                  </group>
                  <group name="Cube_5_7_3" position={[-45, -105, -5]}>
                    <mesh
                      name="Cube_5_7_Mat_0_3"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube_5_7_Mat_0_3.geometry}
                      material={materials.material}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

export default Dinozaur

useGLTF.preload('/hatch_t-rex.glb')



